select
    'ETL_LOAD_DATE'                                 ETL_LOAD_DATE,
    m.HISID                                         ID,
    m.HISID                                         HISID,
    m.Patient_ID                                    Patient_IDStr,
    m.UNUSUAL_FLAG                                  UNUSUAL_FLAG,
    m.ADMISSION_DATE                                SEETLE_TICKS_TIME, --long
    m.DISCHARGE_DATE                                SEETLE_TICKS_DATE, --long
    m.HOSPITAL_ID                                   HOSPITAL_ID,
    4                                               HOSPITAL_LEVEL,
    1                                               theFirstClinicalType,
    21                                              theSecondType,
    m.BENEFIT_TYPE                                  BENEFIT_TYPE,
    'J44.900'                                       DIAGNOSIS_IN,
    m.ADMISSION_DISEASE_NAME                        ADMISSION_DISEASE_NAME,
    'J44.100'                                       DIAGNOSIS_OUT,
    m.DISCHARGE_DISEASE_NAME                        DISCHARGE_DISEASE_NAME,
    ''                                              DIAGNOSIS_ONE,
    m.DISEASE_NAME                                  DISEASE_NAME,
    ''                                              DIAGNOSIS_SECOND,
    m.SECOND_DISEASE_NAME                           SECOND_DISEASE_NAME,
    ''                                              DIAGNOSIS_THIRD,
    m.THIRD_DISEASE_NAME                            THIRD_DISEASE_NAME,
    m.DIAGNOSIS_FOUR                                DIAGNOSIS_FOUR,
    m.DIAGNOSIS_FOUR_NAME                           DIAGNOSIS_FOUR_NAME,
    m.DIAGNOSIS_FIVE                                DIAGNOSIS_FIVE,
    m.DIAGNOSIS_FIVE_NAME                           DIAGNOSIS_FIVE_NAME,
    m.DIAGNOSIS_SIX                                 DIAGNOSIS_SIX,
    m.DIAGNOSIS_SIX_NAME                            DIAGNOSIS_SIX_NAME,
    m.DIAGNOSIS_SEVEN                               DIAGNOSIS_SEVEN,
    m.DIAGNOSIS_SEVEN_NAME                          DIAGNOSIS_SEVEN_NAME,
    m.DIAGNOSIS_EIGHT                               DIAGNOSIS_EIGHT,
    m.DIAGNOSIS_EIGHT_NAME                          DIAGNOSIS_EIGHT_NAME,
    m.DIAGNOSIS_NINE                                DIAGNOSIS_NINE,
    m.DIAGNOSIS_NINE_NAME                           DIAGNOSIS_NINE_NAME,
    m.DIAGNOSIS_TEN                                 DIAGNOSIS_TEN,
    m.DIAGNOSIS_TEN_NAME                            DIAGNOSIS_TEN_NAME,
    m.DIAGNOSIS_ELEVEN                              DIAGNOSIS_ELEVEN,
    m.DIAGNOSIS_ELEVEN_NAME                         DIAGNOSIS_ELEVEN_NAME,
    m.DIAGNOSIS_TWELVE                              DIAGNOSIS_TWELVE,
    m.DIAGNOSIS_TWELVE_NAME                         DIAGNOSIS_TWELVE_NAME,
    m.DIAGNOSIS_THIRTEEN                            DIAGNOSIS_THIRTEEN,
    m.DIAGNOSIS_THIRTEEN_NAME                       DIAGNOSIS_THIRTEEN_NAME,
    m.DIAGNOSIS_FOURTEEN                            DIAGNOSIS_FOURTEEN,
    m.DIAGNOSIS_FOURTEEN_NAME                       DIAGNOSIS_FOURTEEN_NAME,
    m.DIAGNOSIS_FIFTEEN                             DIAGNOSIS_FIFTEEN,
    m.DIAGNOSIS_FIFTEEN_NAME                        DIAGNOSIS_FIFTEEN_NAME,
    m.DIAGNOSIS_SIXTEEN                             DIAGNOSIS_SIXTEEN,
    m.DIAGNOSIS_SIXTEEN_NAME                        DIAGNOSIS_SIXTEEN_NAME,
    m.PATIENT_SEX                                   GENDER,
    m.BMI_CODE                                      BMI_CODE,
    'IsPregnant'                                    IsPregnant, -- false
    'IsLactation'                                   IsLactation, -- false
    m.TOTAL_AMOUNT                                  TOTAL_COST,
    m.BENEFIT_GROUP_ID                              BENEFIT_GROUP_ID,
    ''                                              CKC892,
    m.AUDIT_AUTO_STATUS                             AUDIT_AUTO_STATUS,
    m.BMI_CONVERED_AMOUNT                           BMI_CONVERED_AMOUNT,
    '-1'                                            PatientBenefitGroupCode,
    m.DISCHARGE_REASON                              DISCHARGE_REASON,
    ''                                              BAC021,
    m.BILL_NO                                       BILL_NO,
    'HaveSave'                                      HaveSave,  --true
    m.ADMISSION_DATE                                DJEKD001,
    m.DISCHARGE_DATE                                SETTLE_DATE,
    m.ADMISSION_DATE                                IN_DATE,
    m.DISCHARGE_DATE                                OUT_DATE,
    m.PATIENT_BIRTH                                 PATIENT_BIRTH
from dw_bill m

